/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for XJniDShell */

#ifndef XJniDShell
#define XJniDShell
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_test_dshell_DShell
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_dshell_DShell_nativeInit
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
